version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"  # Cổng mà bạn muốn dùng để truy cập Wordpress, ở đây là cổng 8000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress:/var/www/html  # Mount volume để lưu trữ dữ liệu Wordpress

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress # Thay bằng mật khẩu root cho MySQL của bạn
    volumes:
      - ./db:/var/lib/mysql  # Mount volume để lưu trữ dữ liệu MySQL
